#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/doc-tools-check-languages doc-tools-check-languages /usr/bin/python2-doc-tools-check-languages 300
	update-alternatives --install /usr/bin/doc-tools-update-cli-reference doc-tools-update-cli-reference /usr/bin/python2-doc-tools-update-cli-reference 300
	update-alternatives --install /usr/bin/openstack-auto-commands openstack-auto-commands /usr/bin/python2-openstack-auto-commands 300
	update-alternatives --install /usr/bin/openstack-autohelp openstack-autohelp /usr/bin/python2-openstack-autohelp 300
	update-alternatives --install /usr/bin/openstack-doc-test openstack-doc-test /usr/bin/python2-openstack-doc-test 300
	update-alternatives --install /usr/bin/openstack-generate-docbook openstack-generate-docbook /usr/bin/python2-openstack-generate-docbook 300
	update-alternatives --install /usr/bin/openstack-generate-pot openstack-generate-pot /usr/bin/python2-openstack-generate-pot 300
	update-alternatives --install /usr/bin/openstack-jsoncheck openstack-jsoncheck /usr/bin/python2-openstack-jsoncheck 300
	update-alternatives --install /usr/bin/doc-tools-build-rst doc-tools-build-rst /usr/bin/python2-doc-tools-build-rst 300
	for i in /usr/share/openstack-doc-tools/cleanup/python2-*.py /usr/share/openstack-doc-tools/cleanup/retf/python2-*.py ; do
		FILENAME=`basename $i | sed s/python2-//`
		DIRNAME=`dirname $i`
		update-alternatives --install $DIRNAME/$FILENAME openstack-doc-tools-$FILENAME $i 300
	done
fi

#DEBHELPER#

exit 0
